### ISSUE TITLE
CDN Availability

### ISSUE THREAD

**Issue by nathankitchen** [codemirror/lang-liquid#4]
CodeMirror currently has Liquid support, and I presume it's based on this repo. I'd like to make use of this without too much faffing about, so I was going to include it from the [CDN](https://cdnjs.com/libraries/codemirror).

However, the Liquid language doesn't seem to be a supported mode on the CDN. Is this an oversight, or is there something special about Liquid which means the language mode can't be distributed via the CDN?

**Comment by marijnh** [comment]
I have zero control over what packages cdnjs offers (though I assume they pull from npm, so it's weird if it's not available, but you'll want to ask them, not me).

**Comment by nathankitchen** [comment]
Gotcha, thanks. Didn't realise it wasn't an official release channel, appreciate your time.
