### ISSUE TITLE
Filter autocomplete in {% %} tags not working

### ISSUE THREAD

**Issue by SIMULATAN** [codemirror/lang-liquid#5]
Autocompleting filters within `{% %}` have two major issues:

1. the `liquidCompletionSource` doesn't get the event in the first place as the HTML base interferes
2. in `findContext`, `before` is null instead of `|` when trying to explicitly autocomplete filters

This leads to filter autocompletions (like `upcase`) not working at all in `{% assign name = "test" | <HERE> %}` - instead, the `context` is said to be of `type: "expression"`

**Comment by SIMULATAN** [comment]
Just checked them and couldn't find a direct mention either.
However, there are some examples here: https://shopify.dev/docs/api/liquid/filters.
I've also been using the `append` filter specifically in my `assign` statements: https://github.com/SnotyMe/snoty-backend/blob/2a017fb4b37a7ef46676665cf48438c89b722992/integrations/builtin/src/main/resources/node/integration/ical/node_bottom.liquid#L1-L4.
There, I use https://github.com/bkiers/Liqp as the Liquid implementation.
According to grep.app there's also a good few examples, most notably in the context of `assign` and `if` on GitHub: https://grep.app/search?q=%7B%25+%5B%5E%7D%5D*+%5C%7C+.*%25%7D&regexp=true&filter%5Blang%5D%5B0%5D=Liquid

**Comment by SIMULATAN** [comment]
> Do you know what this {%- -%} syntax is that keeps coming up in these examples?

I've worked with those in my helm templates (which aren't Liquid, but pretty close). Those should be [whitespace controls](https://shopify.github.io/liquid/basics/whitespace/).

**Comment by marijnh** [comment]
Oh right, the `{%-` notation was actually already supported in my syntax.

Attached patch supports filters after `assign`.
